import * as images from "./images/Images";

export const AllProducts = [
  {
    name: "pant",
    price: 150,
    image: images.product1,
    category: "Men",
    description: "",
  },
  {
    name: "String",
    price: 75,
    image: images.product10,
    category: "Women",
    description: "",
  },
  {
    name: "Name",
    price: 50,
    image: images.product11,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 25,
    image: images.product12,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 40,
    image: images.product13,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 39,
    image: images.product14,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 34,
    image: images.product15,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 69,
    image: images.product16,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 69,
    image: images.product17,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 17,
    image: images.product18,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 15,
    image: images.product19,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 200,
    image: images.product20,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 90,
    image: images.product21,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 52,
    image: images.product22,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 37,
    image: images.product2,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 84,
    image: images.product3,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 45,
    image: images.product4,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 124,
    image: images.product5,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 23,
    image: images.product6,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 98,
    image: images.product7,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 62,
    image: images.product8,
    category: "",
    description: "",
  },
  {
    name: "Name",
    price: 54,
    image: images.product9,
    category: "",
    description: "",
  },
];