export { default as bg1 } from "./headerbg1.jpg";
export { default as bg2 } from "./headerbg1.jpg";
export { default as bg3 } from "./headerbg1.jpg";
export { default as product_02 } from "./product_02.jpg";
export { default as product1 } from "./products/p1.png";
export { default as product2 } from "./products/p2.png";
export { default as product3 } from "./products/p3.png";
export { default as product4 } from "./products/p4.png";
export { default as product5 } from "./products/p5.png";
export { default as product6 } from "./products/p6.png";
export { default as product7 } from "./products/p7.png";
export { default as product8 } from "./products/p8.png";
export { default as product9 } from "./products/p9.png";
export { default as product10 } from "./products/p10.png";
export { default as product11 } from "./products/p11.png";
export { default as product12 } from "./products/p12.png";
export { default as product13 } from "./products/p13.png";
export { default as product14 } from "./products/p14.png";
export { default as product15 } from "./products/p15.png";
export { default as product16 } from "./products/p16.png";
export { default as product17 } from "./products/p17.png";
export { default as product18 } from "./products/p18.png";
export { default as product19 } from "./products/p19.png";
export { default as product20 } from "./products/p20.png";
export { default as product21 } from "./products/p21.png";
export { default as product22 } from "./products/p22.png";
export { default as logo } from "./logo_biboshop.jpeg";
export { default as emptyCart } from "./empty_cart.jpg"
export { default as newsletter_img } from "./newsletter.jpg"
export { default as our_role } from "./our_role.jpg"
export { default as why_choose_us } from "./why-choose-us.jpg"
export { default as hero_bg } from "./hero-background.jpg"
